export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";
export const TOGGLE_APPOINTMENT_VISIBILITY = "SHOW_HIDE_APPOINTMENT";
export const SHOW_APPOINTMENT = "SHOW_APPOINTMENT";
export const HIDE_APPOINTMENT = "HIDE_APPOINTMENT";
