export const AUTH_CHECK_USER_REQUEST = "AUTH_CHECK_USER_REQUEST";
export const AUTH_CHECK_USER_SUCCESS = "AUTH_CHECK_USER_SUCCESS";
// Authentication Action Types
export const AUTH_SIGN_IN_REQUEST = "AUTH_SIGN_IN_REQUEST";
export const AUTH_SIGN_IN_SUCCESS = "AUTH_SIGN_IN_SUCCESS";
export const AUTH_SIGN_IN_ERROR = "AUTH_SIGN_IN_ERROR";

export const AUTH_SIGN_OUT_REQUEST = "AUTH_SIGN_OUT_REQUEST";
export const AUTH_SIGN_OUT_SUCCESS = "AUTH_SIGN_OUT_SUCCESS";
export const AUTH_SIGN_OUT_ERROR = "AUTH_SIGN_OUT_ERROR";
