export const ADD_CALENDAR_EVENT_REQUEST = "ADD_CALENDAR_EVENT_REQUEST";
export const ADD_CALENDAR_EVENT_SUCCESS = "ADD_CALENDAR_EVENT_SUCCESS";
export const ADD_CALENDAR_EVENT_ERROR = "ADD_CALENDAR_EVENT_SUCCESS";

export const GET_CALENDAR_EVENT_REQUEST = "GET_CALENDAR_EVENT_REQUEST";
export const GET_CALENDAR_EVENT_SUCCESS = "GET_CALENDAR_EVENT_SUCCESS";
export const GET_CALENDAR_EVENT_ERROR = "GET_CALENDAR_EVENT_SUCCESS";

export const GET_CALENDARS_EVENT_REQUEST = "GET_CALENDARS_EVENT_REQUEST";
export const GET_CALENDARS_EVENT_SUCCESS = "GET_CALENDARS_EVENT_SUCCESS";
export const GET_CALENDARS_EVENT_ERROR = "GET_CALENDARS_EVENT_SUCCESS";
