export const COACHING_LIST_STUDENT_ADD = "COACHING_LIST_STUDENT_ADD";
export const COACHING_LIST_STUDENT_REMOVE = "COACHING_LIST_STUDENT_REMOVE";
export const COACHING_LIST_CLEAR = "COACHING_LIST_CLEAR";

export const ADD_COACHING_ATTENDEE = "ADD_COACHING_ATTENDEE";
export const REMOVE_COACHING_ATTENDEE = "REMOVE_COACHING_ATTENDEE";
export const CLEAR_COACHING_ATTENDEES = "CLEAR_COACHING_ATTENDEES";

export const GET_COACHING_SCHEDULE_REQUEST = "GET_COACHING_SCHEDULE_REQUEST";
export const GET_COACHING_SCHEDULE_SUCCESS = "GET_COACHING_SCHEDULE_SUCCESS";

export const GET_COACHING_SCHEDULES_REQUEST = "GET_COACHING_SCHEDULES_REQUEST";
export const GET_COACHING_SCHEDULES_SUCCESS = "GET_COACHING_SCHEDULES_SUCCESS";

export const ADD_COACHING_SCHEDULE_REQUEST = "ADD_COACHING_SCHEDULE_REQUEST";
export const ADD_COACHING_SCHEDULE_SUCCESS = "ADD_COACHING_SCHEDULE_SUCCESS";

export const UPDATE_COACHING_SCHEDULE_STATUS_REQUEST =
  "UPDATE_COACHING_SCHEDULE_STATUS_REQUEST";
export const UPDATE_COACHING_SCHEDULE_STATUS_SUCCESS =
  "UPDATE_COACHING_SCHEDULE_STATUS_SUCCESS";

export const REQUEST_COACHING_SCHEDULE_REQUEST =
  "REQUEST_COACHING_SCHEDULE_REQUEST";
export const REQUEST_COACHING_SCHEDULE_SUCCESS =
  "REQUEST_COACHING_SCHEDULE_SUCCESS";

export const REMOVE_COACHING_SCHEDULE_REQUEST =
  "REMOVE_COACHING_SCHEDULE_REQUEST";
export const REMOVE_COACHING_SCHEDULE_SUCCESS =
  "REMOVE_COACHING_SCHEDULE_REQUEST";
