export const COACHING_LIST_STUDENT_ADD = "COACHING_LIST_STUDENT_ADD";
export const COACHING_LIST_STUDENT_REMOVE = "COACHING_LIST_STUDENT_REMOVE";
export const COACHING_LIST_CLEAR = "COACHING_LIST_CLEAR";
