export const GET_SUBJECT_FIELDS_REQUEST = "GET_SUBJECT_FIELDS_REQUEST";
export const GET_SUBJECT_FIELDS_SUCCESS = "GET_SUBJECT_FIELDS_SUCCESS";

export const GET_STUDENT_FIELDS_REQUEST = "GET_STUDENT_FIELDS_REQUEST";
export const GET_STUDENT_FIELDS_SUCCESS = "GET_STUDENT_FIELDS_SUCCESS";

export const GET_TEACHER_FIELDS_REQUEST = "GET_TEACHER_FIELDS_REQUEST";
export const GET_TEACHER_FIELDS_SUCCESS = "GET_TEACHER_FIELDS_SUCCESS";
