export const GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";

export const CLEAR_NOTIFICATIONS_REQUEST = "CLEAR_NOTIFICATIONS_REQUEST";
export const CLEAR_NOTIFICATIONS_SUCCESS = "CLEAR_NOTIFICATIONS_SUCCESS";

export const UPDATE_NOTIFICATION_REQUEST = "UPDATE_NOTIFICATION_REQUEST";
export const UPDATE_NOTIFICATION_SUCCESS = "UPDATE_NOTIFICATION_SUCCESS";

export const CHECK_DESKTOP_NOTIFICATION_PERMISSION_REQUEST =
  "CHECK_DESKTOP_NOTIFICATION_PERMISSION_REQUEST";
export const CHECK_DESKTOP_NOTIFICATION_PERMISSION_SUCCESS =
  "CHECK_DESKTOP_NOTIFICATION_PERMISSION_SUCCESS";
