export const SHOW_APPOINTMENT_TOOLTIP = "SHOW_APPOINTMENT_TOOLTIP";
export const HIDE_APPOINTMENT_TOOLTIP = "HIDE_APPOINTMENT_TOOLTIP";
export const UPDATE_APPOINTMENT_META = "UPDATE_APPOINTMENT_META";
