export const ADD_STUDENT_REQUEST = "ADD_STUDENT_REQUEST";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";

export const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";

export const GET_STUDENTS_REQUEST = "GET_STUDENTS_REQUEST";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";

export const GET_STUDENTS_BY_SUBJECT_REQUEST =
  "GET_STUDENTS_BY_SUBJECT_REQUEST";
export const GET_STUDENTS_BY_SUBJECT_SUCCESS =
  "GET_STUDENTS_BY_SUBJECT_SUCCESS";

export const ASSIGN_STUDENT_SUBJECT_REQUEST = "ASSIGN_STUDENT_SUBJECT_REQUEST";
export const ASSIGN_STUDENT_SUBJECT_SUCCESS = "ASSIGN_STUDENT_SUBJECT_SUCCESS";

export const REMOVE_STUDENT_SUBJECT_REQUEST = "REMOVE_STUDENT_SUBJECT_REQUEST";
export const REMOVE_STUDENT_SUBJECT_SUCCESS = "REMOVE_STUDENT_SUBJECT_SUCCESS";
