export const ADD_SUBJECT_REQUEST = "ADD_SUBJECT_REQUEST";
export const ADD_SUBJECT_SUCCESS = "ADD_SUBJECT_SUCCESS";

export const GET_SUBJECT_REQUEST = "GET_SUBJECT_REQUEST";
export const GET_SUBJECT_SUCCESS = "GET_SUBJECT_SUCCESS";

export const GET_SUBJECTS_REQUEST = "GET_SUBJECTS_REQUEST";
export const GET_SUBJECTS_SUCCESS = "GET_SUBJECTS_SUCCESS";

export const GET_SUBJECT_FIELDS_REQUEST = "GET_SUBJECT_FIELDS_REQUEST";
export const GET_SUBJECT_FIELDS_SUCCESS = "GET_SUBJECT_FIELDS_SUCCESS";
