export const ADD_TEACHER_REQUEST = "ADD_TEACHER_REQUEST";
export const ADD_TEACHER_SUCCESS = "ADD_TEACHER_SUCCESS";
export const ADD_TEACHER_ERROR = "ADD_TEACHER_ERROR";

export const GET_TEACHER_REQUEST = "GET_TEACHER_REQUEST";
export const GET_TEACHER_SUCCESS = "GET_TEACHER_SUCCESS";
export const GET_TEACHER_ERROR = "GET_TEACHER_ERROR";

export const GET_TEACHERS_REQUEST = "GET_TEACHERS_REQUEST";
export const GET_TEACHERS_SUCCESS = "GET_TEACHERS_SUCCESS";
export const GET_TEACHERS_ERROR = "GET_TEACHERS_ERROR";

export const ASSIGN_SUBJECT_TEACHER_REQUEST = "ASSIGN_SUBJECT_TEACHER_REQUEST";
export const ASSIGN_SUBJECT_TEACHER_SUCCESS = "ASSIGN_SUBJECT_TEACHER_SUCCESS";
